image: docker:18

services:
  - docker:18-dind

stages:
  - build

variables:
  CI_REGISTRY_IMAGE: altmer/skaro
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
